/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActorImage: typeof import('./src/components/ActorImage.vue')['default']
    Actors: typeof import('./src/components/Actors.vue')['default']
    CardContainer: typeof import('./src/components/CardContainer.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    DetailsTemplate: typeof import('./src/components/DetailsTemplate.vue')['default']
    ExampleCounter: typeof import('./src/components/ExampleCounter.vue')['default']
    ExampleFooter: typeof import('./src/components/ExampleFooter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    ItemCardContainer: typeof import('./src/components/ItemCardContainer.vue')['default']
    LoaderFingers: typeof import('./src/components/LoaderFingers.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    ReviewCardDetailsDialog: typeof import('./src/components/ReviewCardDetailsDialog.vue')['default']
    Reviews: typeof import('./src/components/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
