/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActorImage: typeof import('./src/components/ActorImage.vue')['default']
    Actors: typeof import('./src/components/Actors.vue')['default']
    Badge: typeof import('./src/components/Badge.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CardContainer: typeof import('./src/components/CardContainer.vue')['default']
    DarkList: typeof import('./src/components/DarkList.vue')['default']
    DetailsTemplate: typeof import('./src/components/DetailsTemplate.vue')['default']
    ExampleCounter: typeof import('./src/components/ExampleCounter.vue')['default']
    ExampleFooter: typeof import('./src/components/ExampleFooter.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ItemCard: typeof import('./src/components/ItemCard.vue')['default']
    ItemCardContainer: typeof import('./src/components/ItemCardContainer.vue')['default']
    LoaderFingers: typeof import('./src/components/LoaderFingers.vue')['default']
    MovieCollection: typeof import('./src/components/MovieCollection.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    ReviewCardDetailsDialog: typeof import('./src/components/ReviewCardDetailsDialog.vue')['default']
    Reviews: typeof import('./src/components/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./src/components/ScrollArea.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    VerticalMenu: typeof import('./src/components/VerticalMenu.vue')['default']
  }
}
